import type {
  Task,
  Project,
  Message,
  Meeting,
  FileItem,
  Integration,
  Person,
  NotificationItem,
  ActivityItem,
  Automation,
} from "./types";

export const people: Person[] = [
  { id: "u1", name: "Matthew", initials: "M", role: "Product Designer", color: "blue" },
  { id: "u2", name: "Sarah Chen", initials: "SC", role: "Design Lead", color: "yellow" },
  { id: "u3", name: "Alex Rivera", initials: "AR", role: "Engineer", color: "blue" },
  { id: "u4", name: "Priya Nair", initials: "PN", role: "Marketing", color: "red" },
  { id: "u5", name: "Marcus Webb", initials: "MW", role: "PM", color: "neutral" },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Marketing Launch",
    description: "Q4 campaign launch across web, email, and social.",
    color: "blue",
    progress: 72,
    taskCount: 24,
    completedCount: 18,
    dueDate: "Friday",
    memberIds: ["u1", "u2", "u4"],
    aiSummary:
      "The campaign is progressing well. Two design tasks remain and the launch meeting is scheduled for Friday.",
    status: "on-track",
    progressHistory: [48, 54, 58, 63, 68, 72],
  },
  {
    id: "p2",
    name: "Mobile App Redesign",
    description: "Full visual refresh of the iOS and Android apps.",
    color: "yellow",
    progress: 41,
    taskCount: 32,
    completedCount: 13,
    dueDate: "Oct 12",
    memberIds: ["u1", "u2", "u3"],
    aiSummary:
      "Design is ahead of schedule but engineering is waiting on two API contracts before build can continue.",
    status: "at-risk",
    progressHistory: [22, 28, 33, 36, 38, 41],
  },
  {
    id: "p3",
    name: "Customer Onboarding Revamp",
    description: "Reduce time-to-value for new STACK workspaces.",
    color: "red",
    progress: 18,
    taskCount: 15,
    completedCount: 3,
    dueDate: "Nov 3",
    memberIds: ["u3", "u5"],
    aiSummary:
      "This project is behind schedule. No updates in 6 days and 4 tasks are overdue.",
    status: "behind",
    progressHistory: [10, 12, 14, 15, 16, 18],
  },
  {
    id: "p4",
    name: "Q4 Sales Enablement",
    description: "New pitch deck, case studies, and battlecards.",
    color: "blue",
    progress: 88,
    taskCount: 20,
    completedCount: 17,
    dueDate: "Oct 2",
    memberIds: ["u4", "u5"],
    aiSummary: "Nearly complete. Final review of the pitch deck is the only remaining blocker.",
    status: "on-track",
    progressHistory: [60, 68, 74, 80, 85, 88],
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Finish product proposal",
    description: "Incorporate feedback from Marcus and finalize the pricing section.",
    done: false,
    priority: "urgent",
    projectId: "p1",
    assigneeId: "u1",
    dueDate: "Today, 5:00 PM",
    labels: ["writing"],
    subtasks: [
      { id: "st1", title: "Add pricing table", done: true },
      { id: "st2", title: "Get legal sign-off", done: false },
    ],
    source: "notion",
    createdAt: "2 days ago",
  },
  {
    id: "t2",
    title: "Review marketing designs",
    description: "Check the new landing page mocks from Sarah.",
    done: false,
    priority: "important",
    projectId: "p1",
    assigneeId: "u1",
    dueDate: "Today, 2:00 PM",
    labels: ["design"],
    subtasks: [],
    source: "stack",
    createdAt: "1 day ago",
  },
  {
    id: "t3",
    title: "Prepare for 2 PM meeting",
    description: "Pull together talking points for the launch sync.",
    done: false,
    priority: "urgent",
    projectId: "p1",
    assigneeId: "u1",
    dueDate: "Today, 1:30 PM",
    labels: ["meeting"],
    subtasks: [],
    source: "google-calendar",
    createdAt: "Today",
  },
  {
    id: "t4",
    title: "Approve API contract for redesign",
    done: false,
    priority: "important",
    projectId: "p2",
    assigneeId: "u3",
    dueDate: "Tomorrow",
    labels: ["engineering"],
    subtasks: [
      { id: "st3", title: "Review auth endpoints", done: true },
      { id: "st4", title: "Confirm rate limits", done: false },
    ],
    source: "github",
    createdAt: "3 days ago",
  },
  {
    id: "t5",
    title: "Write onboarding email sequence",
    done: false,
    priority: "normal",
    projectId: "p3",
    assigneeId: "u5",
    dueDate: "Friday",
    labels: ["copy"],
    subtasks: [],
    source: "stack",
    createdAt: "5 days ago",
  },
  {
    id: "t6",
    title: "Finalize Q4 pitch deck",
    done: false,
    priority: "urgent",
    projectId: "p4",
    assigneeId: "u4",
    dueDate: "Overdue by 1 day",
    labels: ["sales"],
    subtasks: [],
    source: "drive",
    createdAt: "6 days ago",
  },
  {
    id: "t7",
    title: "Sync design tokens with engineering",
    done: true,
    priority: "normal",
    projectId: "p2",
    assigneeId: "u2",
    dueDate: "Yesterday",
    labels: ["design"],
    subtasks: [],
    source: "github",
    createdAt: "4 days ago",
  },
  {
    id: "t8",
    title: "Book venue for launch event",
    done: true,
    priority: "normal",
    projectId: "p1",
    assigneeId: "u4",
    dueDate: "2 days ago",
    labels: [],
    subtasks: [],
    source: "stack",
    createdAt: "1 week ago",
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    source: "slack",
    from: "Sarah Chen",
    subject: "#marketing-launch",
    preview: "Can you take a look at the new hero section before EOD?",
    time: "9m ago",
    urgent: true,
    unread: true,
    bucket: "urgent",
  },
  {
    id: "m2",
    source: "gmail",
    from: "Legal Team",
    subject: "Re: Product proposal — sign-off needed",
    preview: "One clause needs a small edit before we can approve this.",
    time: "34m ago",
    urgent: true,
    unread: true,
    bucket: "urgent",
  },
  {
    id: "m3",
    source: "teams",
    from: "Marcus Webb",
    subject: "Onboarding revamp",
    preview: "We should regroup on the timeline this week, it's slipping.",
    time: "1h ago",
    urgent: false,
    unread: true,
    bucket: "today",
  },
  {
    id: "m4",
    source: "gmail",
    from: "Priya Nair",
    subject: "Q4 pitch deck — final pass",
    preview: "Attached the deck with the updated case studies section.",
    time: "2h ago",
    urgent: false,
    unread: false,
    bucket: "today",
  },
  {
    id: "m5",
    source: "slack",
    from: "#eng-mobile",
    subject: "API contract discussion",
    preview: "Alex posted the updated schema, please review by tomorrow.",
    time: "3h ago",
    urgent: false,
    unread: true,
    bucket: "this-week",
  },
  {
    id: "m6",
    source: "outlook",
    from: "HubSpot Notifications",
    subject: "3 new leads assigned to you",
    preview: "You have 3 new leads from the Q4 campaign landing page.",
    time: "Yesterday",
    unread: false,
    urgent: false,
    bucket: "this-week",
  },
  {
    id: "m7",
    source: "gmail",
    from: "GitHub",
    subject: "[stack/app] PR #482 merged",
    preview: "design-tokens-sync was merged into main by Alex Rivera.",
    time: "2 days ago",
    urgent: false,
    unread: false,
    bucket: "later",
  },
];

export const meetings: Meeting[] = [
  {
    id: "e1",
    title: "Launch readiness sync",
    time: "2:00 PM",
    durationMin: 30,
    source: "google-calendar",
    attendees: ["Sarah Chen", "Priya Nair", "Matthew"],
    projectId: "p1",
    relatedTasks: 3,
    link: "meet.stack.app/launch-sync",
  },
  {
    id: "e2",
    title: "1:1 with Marcus",
    time: "3:30 PM",
    durationMin: 30,
    source: "outlook-calendar",
    attendees: ["Marcus Webb", "Matthew"],
    relatedTasks: 0,
  },
  {
    id: "e3",
    title: "Mobile redesign review",
    time: "4:15 PM",
    durationMin: 45,
    source: "zoom",
    attendees: ["Sarah Chen", "Alex Rivera", "Matthew"],
    projectId: "p2",
    relatedTasks: 2,
    link: "zoom.us/j/9021174",
  },
  {
    id: "e4",
    title: "Sales enablement check-in",
    time: "Tomorrow, 10:00 AM",
    durationMin: 30,
    source: "google-calendar",
    attendees: ["Priya Nair", "Marcus Webb"],
    projectId: "p4",
    relatedTasks: 1,
  },
];

export const files: FileItem[] = [
  { id: "f1", name: "Q4 Marketing Plan.pdf", kind: "pdf", source: "drive", owner: "Priya Nair", updatedAt: "2h ago", size: "4.2 MB", favorite: true },
  { id: "f2", name: "Launch Landing Page.fig", kind: "image", source: "dropbox", owner: "Sarah Chen", updatedAt: "5h ago", size: "18 MB" },
  { id: "f3", name: "Mobile Redesign Spec", kind: "doc", source: "notion", owner: "Sarah Chen", updatedAt: "Yesterday", size: "—" },
  { id: "f4", name: "Sales Pitch Deck v9.pptx", kind: "slide", source: "onedrive", owner: "Marcus Webb", updatedAt: "Yesterday", size: "22 MB", favorite: true },
  { id: "f5", name: "Onboarding Metrics.xlsx", kind: "sheet", source: "drive", owner: "Alex Rivera", updatedAt: "2 days ago", size: "1.1 MB" },
  { id: "f6", name: "Brand Assets", kind: "folder", source: "drive", owner: "Sarah Chen", updatedAt: "3 days ago", size: "142 items" },
  { id: "f7", name: "API Contract Draft.md", kind: "doc", source: "github", owner: "Alex Rivera", updatedAt: "3 days ago", size: "12 KB" },
];

export const integrations: Integration[] = [
  { id: "gmail", name: "Gmail", category: "Work", description: "Sync your inbox and surface important email.", connected: true, lastSynced: "Just now", accent: "red" },
  { id: "outlook", name: "Outlook", category: "Work", description: "Connect Outlook mail and contacts.", connected: false, accent: "blue" },
  { id: "slack", name: "Slack", category: "Work", description: "Bring important channels and DMs into STACK.", connected: true, lastSynced: "2m ago", accent: "yellow" },
  { id: "teams", name: "Microsoft Teams", category: "Work", description: "Sync Teams chats and channels.", connected: false, accent: "blue" },
  { id: "zoom", name: "Zoom", category: "Work", description: "Turn meetings into summaries and tasks.", connected: true, lastSynced: "1h ago", accent: "blue" },
  { id: "notion", name: "Notion", category: "Work", description: "Index docs and wikis for AI search.", connected: true, lastSynced: "10m ago", accent: "neutral" },
  { id: "github", name: "GitHub", category: "Work", description: "Track PRs, issues, and releases.", connected: true, lastSynced: "5m ago", accent: "neutral" },
  { id: "drive", name: "Google Drive", category: "Files", description: "Search and preview your Drive files.", connected: true, lastSynced: "Just now", accent: "blue" },
  { id: "dropbox", name: "Dropbox", category: "Files", description: "Bring Dropbox files into universal search.", connected: true, lastSynced: "3h ago", accent: "blue" },
  { id: "onedrive", name: "OneDrive", category: "Files", description: "Sync files stored in OneDrive.", connected: false, accent: "blue" },
  { id: "box", name: "Box", category: "Files", description: "Connect Box for enterprise file storage.", connected: false, accent: "neutral" },
  { id: "google-calendar", name: "Google Calendar", category: "Calendar", description: "See events alongside tasks and deadlines.", connected: true, lastSynced: "Just now", accent: "red" },
  { id: "outlook-calendar", name: "Outlook Calendar", category: "Calendar", description: "Bring Outlook events into your unified calendar.", connected: false, accent: "blue" },
  { id: "trello", name: "Trello", category: "Productivity", description: "Sync boards and cards as STACK tasks.", connected: false, accent: "blue" },
  { id: "asana", name: "Asana", category: "Productivity", description: "Two-way sync with Asana projects.", connected: true, lastSynced: "20m ago", accent: "red" },
  { id: "hubspot", name: "HubSpot", category: "CRM", description: "Surface deals, leads, and CRM activity.", connected: true, lastSynced: "1h ago", accent: "red" },
  { id: "salesforce", name: "Salesforce", category: "CRM", description: "Connect accounts, opportunities, and contacts.", connected: false, accent: "blue" },
  { id: "shopify", name: "Shopify", category: "CRM", description: "Track store orders and performance.", connected: false, accent: "yellow" },
  { id: "stripe", name: "Stripe", category: "Payments / Finance", description: "See payments and subscription activity.", connected: false, accent: "blue" },
  { id: "paypal", name: "PayPal", category: "Payments / Finance", description: "Track PayPal transactions.", connected: false, accent: "blue" },
  { id: "quickbooks", name: "QuickBooks", category: "Payments / Finance", description: "Sync invoices and financial records.", connected: false, accent: "neutral" },
  { id: "okta", name: "Okta", category: "Identity", description: "Enterprise SSO for your workspace.", connected: false, accent: "neutral" },
];

export const notifications: NotificationItem[] = [
  { id: "n1", title: "3 tasks assigned to you", count: 3, time: "10m ago", kind: "task" },
  { id: "n2", title: "New messages in #marketing-launch", count: 5, time: "25m ago", kind: "message" },
  { id: "n3", title: "Meeting starting soon", count: 1, time: "40m ago", kind: "meeting" },
  { id: "n4", title: "Marketing Launch updated", count: 2, time: "1h ago", kind: "project" },
];

export const activity: ActivityItem[] = [
  { id: "a1", actor: "Sarah Chen", action: "completed", target: "Homepage Design", time: "12m ago" },
  { id: "a2", actor: "Alex Rivera", action: "created a new task in", target: "Mobile App Redesign", time: "38m ago" },
  { id: "a3", actor: "Priya Nair", action: "updated", target: "Q4 Sales Enablement", time: "1h ago" },
  { id: "a4", actor: "Marcus Webb", action: "commented on", target: "Customer Onboarding Revamp", time: "2h ago" },
  { id: "a5", actor: "STACK AI", action: "generated a summary for", target: "Launch readiness sync", time: "3h ago" },
];

export const automations: Automation[] = [
  {
    id: "au1",
    name: "Meeting → Tasks",
    enabled: true,
    runs: 128,
    steps: [
      { id: "s1", kind: "trigger", label: "When", detail: "A meeting ends" },
      { id: "s2", kind: "ai", label: "STACK AI", detail: "Summarize meeting" },
      { id: "s3", kind: "find", label: "Find", detail: "Action items" },
      { id: "s4", kind: "action", label: "Create", detail: "Tasks" },
      { id: "s5", kind: "action", label: "Update", detail: "Project" },
      { id: "s6", kind: "notify", label: "Notify", detail: "Team" },
    ],
  },
  {
    id: "au2",
    name: "Urgent email → Slack alert",
    enabled: true,
    runs: 54,
    steps: [
      { id: "s1", kind: "trigger", label: "When", detail: "New urgent email" },
      { id: "s2", kind: "action", label: "Create", detail: "Task" },
      { id: "s3", kind: "notify", label: "Notify", detail: "You on Slack" },
    ],
  },
  {
    id: "au3",
    name: "Deadline approaching digest",
    enabled: false,
    runs: 12,
    steps: [
      { id: "s1", kind: "trigger", label: "When", detail: "Deadline approaching" },
      { id: "s2", kind: "ai", label: "STACK AI", detail: "Generate report" },
      { id: "s3", kind: "notify", label: "Notify", detail: "Project owner" },
    ],
  },
];

export const dailyBrief = {
  greetingMeetings: 3,
  greetingTasks: 5,
  greetingUpdates: 2,
  focus: [
    "Finish product proposal",
    "Review marketing designs",
    "Prepare for 2 PM meeting",
  ],
};
